name: irccloud-desktop
version: 0.5.1
summary: IRCCloud Desktop App
description: |
  IRCCloud Desktop App
icon: irccloud-desktop.png

grade: stable
confinement: strict

parts:
  irccloud-desktop:
    plugin: dump
    source: https://github.com/irccloud/irccloud-desktop/releases/download/v0.5.1/irccloud-desktop_0.5.1_amd64.deb
    source-type: deb
    prepare: |
      sed -i 's@Icon=irccloud-desktop@Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/irccloud-desktop.png@' usr/share/applications/irccloud-desktop.desktop
      execstack --clear-execstack opt/IRCCloud/irccloud-desktop
    build-packages:
      - execstack
    after:
      - desktop-gtk2
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  irccloud-desktop:
    command: bin/desktop-launch $SNAP/opt/IRCCloud/irccloud-desktop
    desktop: usr/share/applications/irccloud-desktop.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - pulseaudio
      - unity7
      - wayland
      - x11
